# build requirements and time estimates are defined here
# and loaded by ProductionEstimation class.
#
# time estimates from units.lua.  For example, for a town hall the costs are
# defined as Costs = {"time", 255, "gold", 1200, "wood", 800}.  To
# get the game time, multiply the "time" by 6.
#
#
!!orst.stratagusai.prodh.ProductionReqs
requirements:
  #
  # buildings
  #
  "unit-town-hall": &town-hall
    preconditions: !!set
      ? &peasant {preconditions: !!set { ? *town-hall : null}, time: 270, type: "unit-peasant"}
      : null
    producer: unit-peasant
    time: 1530
    type: "unit-town-hall"
  "unit-farm": &farm
    preconditions: !!set
      ? *peasant
      : null
    producer: unit-peasant
    time: 400
    type: "unit-farm"
  "unit-human-barracks": &barracks
    preconditions: !!set
      ? *peasant
      : null
    producer: unit-peasant
    time: 1200
    type: "unit-human-barracks"
  "unit-elven-lumber-mill": &lumber-mill
    preconditions: null
    producer: unit-peasant
    time: 900
    type: "unit-elven-lumber-mill"
  "unit-human-blacksmith": &blacksmith
    preconditions: !!set
      ? *peasant
      : null
    producer: unit-peasant
    time: 1200
    type: "unit-human-blacksmith"
  "unit-keep": &keep
    preconditions: !!set
      ? *town-hall
      : null
    producer: unit-peasant
    time: 1200
    type: "unit-keep"
  "unit-stables": &stables
    preconditions: !!set
      ? *keep
      : null
    producer: unit-peasant
    time: 900
    type: "unit-stables"
  #
  # combat units
  #
  "unit-footman": &footman
    preconditions: !!set
      ? *barracks
      : null
    producer: unit-human-barracks
    time: 360
    type: "unit-footman"
  "unit-peasant": *peasant
  "unit-ballista": &ballista
    preconditions: !!set
      ? *barracks
      : null
    time: 1500
    type: "unit-ballista"
  "unit-knight": &knight
    preconditions: !!set
      ? *barracks
      ? *blacksmith
      ? *stables
      : null
    time: 540
    type: "unit-knight"
  "unit-archer": &archer
    preconditions: !!set
      ? *barracks
      ? *lumber-mill
      : null
    producer: unit-human-barracks
    time: 420
    type: "unit-archer"
